api_version = "2025-01"

[[extensions]]
type = "ui_extension"
name = "Order action button"
handle = "buyer-subscriptions-oa"

[[extensions.targeting]]
module = "../buyer-subscriptions/src/OrderActionMenuItem/OrderActionMenuItem.tsx"
target = "customer-account.order.action.menu-item.render"

[extensions.capabilities]
api_access = true
